---
- name: Install apt-transport-https
  apt: name=apt-transport-https state=present
  become: True

- name: Add Docker Key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  become: True

- name: Add Docker Repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present
  become: True

- name: Install Docker
  apt: name=docker-engine state=present update_cache=yes
  become: True

- name: Install Python Docker lib
  apt: name=python-docker state=present
  become: True

- name: Add user to docker group
  user:
   name: "{{ ansible_ssh_user }}"
   groups: docker
   append: yes
  become: True

- name: Configure dockerd for local registry (part 1)
  file:
   path: /etc/systemd/system/docker.service.d
   state: directory
  become: True

- name: Configure dockerd for local registry (part 2)
  blockinfile:
    dest: /etc/systemd/system/docker.service.d/docker.conf
    create: yes
    block: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/docker daemon -H fd:// --insecure-registry 172.42.42.1

- name: Configure mount for local registry
  file:
   path: /mnt/registry
   state: directory

- name: Start private registry
  docker_container:
    name: registry
    image: registry:2
    restart: yes
    ports:
      - "5000:5000"
    volumes:
      - "/mnt/registry:/var/lib/registry"

   
