---
- name: Configure Apt for Proxy
  blockinfile:
    dest: /etc/apt/apt.conf.d/30proxy
    create: yes
    block: |
      Acquire::http::proxy::rtp-linux.cisco.com "DIRECT";
      Acquire::http::proxy "http://proxy.esl.cisco.com:80";
      Acquire::https::proxy "http://proxy.esl.cisco.com:80";
  become: True

- name: Configure system for Proxy
  blockinfile:
    dest: /etc/environment
    block: |
      http_proxy=http://proxy.esl.cisco.com:80/
      https_proxy=http://proxy.esl.cisco.com:80/
      no_proxy="localhost,127.0.0.1,.cisco.com,{{ no_proxy_ips }}"
  become: True

- name: Configure luser for Proxy
  blockinfile:
    dest: /home/luser/.bash_profile
    block: |
     export http_proxy=http://proxy.esl.cisco.com:80/
     export https_proxy=http://proxy.esl.cisco.com:80/
     no_proxy="localhost,127.0.0.1,.cisco.com,{{ no_proxy_ips }}"
    create: yes
  become: True

- name: Change DNS resolver precedence for IPv4
  blockinfile:
    dest: /etc/gai.conf
    block: precedence ::ffff:0:0/96  100
  become: True

- name: Configure Test Net Interface
  blockinfile:
    dest: /etc/network/interfaces.d/{{ testnet_interface }}.{{ testnet_vlanid }}
    block: |
          auto {{ testnet_interface }}.{{ testnet_vlanid }} 
          iface {{ testnet_interface }}.{{ testnet_vlanid }} inet static 
             vlan-raw-device {{ testnet_interface }} 
             address {{ testnet_ip }}
             netmask {{ testnet_netmask }}
    create: yes
  become: True
  when: raw_interface

- name: Enable Test Net Interface
  command: ifup {{ testnet_interface }}.{{ testnet_vlanid }} 
  become: True
  when: raw_interface

- include: bridge_plugin.yml
  when: bridge_interface

- name: Remove apparmor restrictions on libvirtd
  command: apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
  become: True
  ignore_errors: True

   
