---

- include: bridge_plugin.yml
  when: bridge_interface

- name: Remove apparmor restrictions on libvirtd
  command: apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
  become: True
  ignore_errors: True

   
