---
- name: Configure mount for local registry
  file:
   path: /mnt/registry
   state: directory
  become: True

- name: Start private registry
  docker_container:
    name: registry
    image: registry:2
    restart: yes
    ports:
      - "5000:5000"
    volumes:
      - "/mnt/registry:/var/lib/registry"
  become: True

